#!/usr/bin/env bash
set -euo pipefail

WRAPPER="slurm/berzelius_short_train_pulled_image.sh"

EXPORTS="ALL"
EXPORTS+=",MODEL_ID=HuggingFaceTB/SmolLM-135M-Instruct"
EXPORTS+=",TOKENIZER_CONFIG=configs/tokenizers/default.yaml"
EXPORTS+=",SFT_FORMAT=prompt_completion"
EXPORTS+=",USE_CHAT_TEMPLATE=true"
EXPORTS+=",DATA_MAX_SAMPLES=0"
EXPORTS+=",MAX_LENGTH=1024"
EXPORTS+=",PER_DEVICE_TRAIN_BATCH_SIZE=8"
EXPORTS+=",GRADIENT_ACCUMULATION_STEPS=2"
EXPORTS+=",GRADIENT_CHECKPOINTING=false"
EXPORTS+=",GROUP_BY_LENGTH=true"
EXPORTS+=",PACKING=false"
EXPORTS+=",LOSS_TYPE=nll"
EXPORTS+=",LOAD_BEST_MODEL_AT_END=false"
EXPORTS+=",SAVE_TOTAL_LIMIT=2"
EXPORTS+=",CANONICALIZE_SMILES=true"
EXPORTS+=",EVALUATION_RUN_AFTER_TRAINING=true"
EXPORTS+=",EVALUATION_SPLIT=validation"
EXPORTS+=",EVALUATION_MAX_VALIDATION_EXAMPLES=128"
EXPORTS+=",GENERATION_MAX_NEW_TOKENS=128"
EXPORTS+=",LEARNING_RATE=0.00002"
EXPORTS+=",MAX_STEPS=4000"

sbatch \
  --job-name=smollm-default-grouped-probe \
  --time=04:00:00 \
  --export="$EXPORTS" \
  "$WRAPPER"
